name: Run ESLint on Pull Requests

on: 
  - pull_request

jobs:
  lint:
    name: Lint source code
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source
        uses: actions/checkout@v3.0.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1

      - name: Install dependencies
        run: npm ci

      - name: Lint the source
        run: npm run lint

      - name: Use Node.js
        uses: actions/setup-node@master
        with:
          node-version: 16.x